# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages

bioc_required: true

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
