# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname MultivariateSpecial
#' @return \code{lgammap} is the log multivariate gamma function. 
#' @note For \code{lgammp}, warnings of the type \code{"value out of range in 
#'   'lgamma'"} is due to evaluation in the half integers below \eqn{(p-1)/2}.
#' @export
lgammap <- function(x, p = 1L) {
    .Call('_Bmisc_lgammap', PACKAGE = 'Bmisc', x, p)
}

